### ISSUE TITLE
Email broken with Generic Subject + base64 encoding

### ISSUE THREAD

**Issue by Zaczero** [simple-login/app#334]
I am facing an issue where my mail client is unable to decode decrypted message as Content-Transfer-Encoding header is invalid. After disabling Generic Subject feature everything started to work as normal.

![image](https://user-images.githubusercontent.com/10835147/100154966-bde0b080-2ea6-11eb-9791-4dea80ea2497.png)

A message source for reference _(what is rendered by my mail client)_:
```
Content-Type: multipart/signed; protocol="application/pgp-signature";
 micalg="pgp-sha256"; boundary="===============5001150447241688545=="
MIME-Version: 1.0

--===============5001150447241688545==
MIME-Version: 1.0
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64


<table width="100%" style="width: 100%; -premailer-width: 100%; -premailer-cellpadding: 0; -premailer-cellspacing: 0; margin: 0; padding: 0;">
    <tr>
        <td style="border-bottom:1px dashed #5675E2; padding: 10px 0px">Forwarded by SimpleLogin to *** with *** as subject</td>
    </tr>
    <tr>
        <td>IA0KDQo8IS0tR0xPQkFMX0VMRU1FTlRTL1JUTV9HTE9CQUxfRUxFTUVOVFMtLT48dGFibGUgc3R5
bGU9Im1pbi13aWR0aDogMTAwJTsgIiBjbGFzcz0ic3R5bGluZ2Jsb2NrLWNvbnRlbnQtd3JhcHBl
ciIgd2lkdGg9IjEwMCUiIGNlbGxzcGFjaW5nPSIwIiBjZWxscGFkZGluZz0iMCI+PHRyPjx0ZCBj
bGFzcz0ic3R5bGluZ2Jsb2NrLWNvbnRlbnQtd3JhcHBlciBjYW1hcmtlci1pbm5lciI+PC90ZD48
...
```

You can see how the Generic Subject feature is not respecting current Content-Transfer-Encoding header as it uses no encoding at all for _(most likely)_ every message relied _(it includes original subject at the beginning of a message)_.

**Comment by nguyenkims** [comment]
Thanks for reporting the issue! It should be fixed with https://github.com/simple-login/app/pull/337

**Comment by Zaczero** [comment]
I have just had a chance to test the changes and unfortunately it is still broken. @nguyenkims 

If you want to prepend some text to a message body you cannot simply base64 encode it and then concat. You must decode the whole body, concat the message and then encode everything together (or just strip the whole encoding for simplicity - may break some mails though).

From my message analysis it looks like there is some base64 encoding going on, however it is invalid resulting in a message being still unreadable. Example:

```
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: base64
Content-Id: <e65ada7a-1356-4a8f-93d4-cdb5cbf7fd5e>

Cjx0YWJsZSB3aWR0aD0iMTAwJSIgc3R5bGU9IndpZHRoOiAxMDAlOyAtcHJlbWFpbGVyLXdpZHRoOiAxMDAlOyAtcHJlbWFpbGVyLWNlbGxwYWRkaW5nOiAwOyAtcHJlbWFpbGVyLWNlbGxzcGFjaW5nOiAwOyBtYXJnaW46IDA7IHBhZGRpbmc6IDA7Ij4KICAgIDx0cj4KICAgICAgICA8dGQgc3R5bGU9ImJvcmRlci1ib3R0b206MXB4IGRhc2hlZCAjNTY3NUUyOyBwYWRkaW5nOiAxMHB4IDBweCI+Rm9yd2FyZGVkIGJ5IFNpbXBsZUxvZ2luIHRvIDA4NmM4YTJiLWMzNzgtNGRlZC05M2Y1LTBjNjUxMWJmMDgzMkByZWxheS5tb25pY3oucGwgd2l0aCA8Yj5FbWFpbCBhZGRyZXNzIGNoYW5nZTwvYj4gYXMgc3ViamVjdDwvdGQ+CiAgICA8L3RyPgogICAgPHRyPgogICAgICAgIDx0ZD4=PCFET0NUWVBFIGh0bWw+CjxodG1sIGRpcj0ibHRyIiBzdHlsZT0iLW1zLXRleHQtc2l6ZS1h
ZGp1c3Q6IG5vbmU7IC13ZWJraXQtdGV4dC1zaXplLWFkanVzdDogbm9uZTsgaGVpZ2h0OiAx
MDAlOyI+CiAgPGhlYWQ+CiAgICA8bWV0YSBodHRwLWVxdWl2PSJDb250ZW50LVR5cGUiIGNv
bnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD1VVEYtOCI...
```

This is how current message source looks like. You can see the very long first line which consists of both prepended message and the original 1st line. You can actually spot the current concatenation at the place `Dx0ZD4= <pre, post> PCFET`. It's easy to find as base64 messages usually end with `=` character. Which further confirms my theory about incorrect base64 message prepend.

**Comment by nguyenkims** [comment]
@Zaczero you're right, the text is appended via a simple string concatenation indeed. This doesn't cause issue with our PGP client  (GPGTools for Mail Mac) but seems to not work reliably on Protonmail. Do you have a way to reproduce this issue? I'm working on a fix and I can use this for testing it :)

**Comment by Zaczero** [comment]
The client I use is MS Outlook. Proton bridge just takes care about decryption of a message so I believe you should be able to reproduce it with just the client alone. Alternatively you can test if your message body is being decoded with some base64 decode tool like https://www.base64decode.org/ Please note that there is a slight chance that even with invalid base64 encoding the decoded output will be readable. Make sure to test your code with a few different message bodies.

The thing is that base64 uses 3 characters for encoding 2 bytes. If there is an improper encoding like in the example above at most 2 bytes will be corrupted (one block). At best nothing else will be affected. At worst the whole math after the point with invalid encoding will be screwed up. That's just how it is. And that's why you may have not catched this issue during your testing.

**Comment by Zaczero** [comment]
And here is a video visualizing my point.
[201217025414_b7df18.zip](https://github.com/simple-login/app/files/5706494/201217025414_b7df18.zip)

_notice how adding/changing 1 character is enough to make the whole output 99.99% readable._

**Comment by nguyenkims** [comment]
@Zaczero this issue should been fixed now. Can you let me know if the problem persists? Thanks :)

**Comment by Zaczero** [comment]
@nguyenkims Thank you for a quick fix. However, I will not be able to test the changes personally. You can learn more by checking the `hi@simplelogin.io` mailbox.
